### PR TITLE
feat: add feature serde_derive

### PR DESCRIPTION
**Pull request by Sherlock-Holo**
dns-over-https has JSON format, If we can serialize `dns-message-parser` struct to JSON, that will be more user-friendly.

### CODE REVIEW

**Comment by LinkTed** [comment]
Thanks for your contribution. Can you show me where the JSON format is defined for `dns-over-https`? And if it is possible to post an example of the JSON format.

**Comment by Sherlock-Holo** [comment]
https://developers.google.com/speed/public-dns/docs/doh/json
Google define a json version doh. Although doh have a rfc 8484 and use the wire format, the json version still have a lot of users and many doh providers provide json version and rfc version service, such as Google, cloudflare

**Comment by LinkTed** [comment]
It seems that the code cannot be compiled, because the `use serde::{Deserialize, Serialize};
` statements are missing. Could you please fix it and add some test cases? Nevertheless, thanks for your support.

**Comment by Sherlock-Holo** [comment]
> It seems that the code cannot be compiled, because the `use serde::{Deserialize, Serialize}; ` statements are missing. Could you please fix it and add some test cases? Nevertheless, thanks for your support.

compile error is fixed now.

What test cases should I add? IMO this PR only add serde dervie and it won't cause problem normally, if an error happened, the problem should belong to crate `serde` 🤔

**Comment by LinkTed** [comment]
For example, how to serialize and deserialize a DNS packet to JSON and vice versa, by using `serde_json` crate. I think that this code would not produce a JSON like your [Google](https://developers.google.com/speed/public-dns/docs/doh/json) example or like the RFC [draft](https://tools.ietf.org/html/draft-bortzmeyer-dns-json-01).

**Comment by Sherlock-Holo** [comment]
You are right, this code would not produce a Google DoH JSON. I thought add derive `Deserialize, Serialize` to `dns-message-parser` struct can make it easy parse Google DoH JSON, but it seems I was wrong 🙈

**Pull request closed without merging**
